apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-metrics
  namespace: fullstack-app
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
  - port: 8000
    path: /metrics
    interval: 15s

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: fullstack-app
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'backend'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: backend
        action: keep
      - source_labels: [__meta_kubernetes_pod_container_port_number]
        regex: "8000"
        action: keep
